### ISSUE TITLE
OnlineIndexer does not backoff properly when it retries

### ISSUE THREAD

**Issue by nblintao** [FoundationDB/fdb-record-layer#1007]
The delay is converging to 0 instead.

**Comment by nblintao** [comment]
Now I'm looking at `FDBDatabaseRunnerImpl`. It has the same problem as well. I will just put the change in https://github.com/FoundationDB/fdb-record-layer/pull/813.

**Comment by nblintao** [comment]
@alecgrieser I was wondering if it was noticeable that `DatabaseRunner` had never backed off properly? (If I do math correctly) I think the current behavior is retrying every 10 ms, rather than backing off to at maximum 1000 ms.

**Comment by alecgrieser** [comment]
That's definitely possible. I'm not sure we have data confirming or denying that.

**Comment by nblintao** [comment]
@alecgrieser I see. I asked because I was wondering if we'll be lucky to see performance improvement (by reducing conflicts) after adopting the fix, or we would see regressions on at least some types of traffic because it was relying on that behavior?

**Comment by alecgrieser** [comment]
I guess it depends. I think you'd probably see both--some things get better throughput because of more correctly spreading around things to reduce conflicts, and some things will see higher latency because of more of a delay. Which is probably fine--no such thing as free lunch.
