### ISSUE TITLE
PlanHash for LiteralKeyExpression is not stable

### ISSUE THREAD

**Issue by ohadzeliger** [FoundationDB/fdb-record-layer#1087]
`planHash()` value for `LiteralKeyExpression` (and by extension `queryHash` as well) are using `proto.hashCode()` delegation which is not stable between JVMs. The `proto.hashCode()` implementation comes our different every time the JVM is recycled (e.g. when a test is rerun) and can therefore not be used for matching queries to plans.
A different method for calculating `planHash` and `queryHash` should be used, e.g. use the value as the base.

**Comment by MMcM** [comment]
Dupe of #1066?

**Comment by ohadzeliger** [comment]
Yes. Same problem, different source.
