### ISSUE TITLE
Address follow-up issues in Lucene Index implementation

### ISSUE THREAD

**Issue by scgray** [FoundationDB/fdb-record-layer#1129]
In https://github.com/FoundationDB/fdb-record-layer/pull/1121, @ScottDugas had a number of suggestions at the end of the discussion that would be worth addressing.  In particular, there are some real concerns about the fact that blocking API calls are made within futures -- these can (and have) resulted in deadlocks by exhausting the main execution thread pool waiting for futures to complete (that couldn't be serviced because the threads were tied up).  The code is probably fine as it stands for benchmarking and testing, but as it matures this needs to be addressed.

**Comment by alecgrieser** [comment]
See also #1128
