### ISSUE TITLE
integrate boolean normalization into planning process

### ISSUE THREAD

**Issue by normen662** [FoundationDB/fdb-record-layer#1301]
The cascades planner currently just calls the boolean normalizer prior to planning in order to convert the filter predicate into its CNF. While that's great most of the time we can also miss out on some plans:

From `FDBOrToUnionTest.testOrQueryNoIndex`:

```
QueryComponent orComponent = Query.or(
                Query.field("num_value_3_indexed").equalsValue(1),
                Query.field("num_value_3_indexed").equalsValue(2),
                Query.field("num_value_3_indexed").equalsValue(4));
        RecordQuery query = RecordQuery.newBuilder()
                .setRecordType("MySimpleRecord")
                .setFilter(Query.and(Query.field("str_value_indexed").equalsValue("even"), orComponent))
                .build();
```

The desired plan is an index scan over `MySimpleRecord` ranged `["even", "even"]` followed by filtering using one predicate applying the three-legged _or_ term.

We have a predicate of the form `a ^ (x v y v z)` which is CNFed into: `(a ^ x) v (a ^ y) v (a ^ z)`. That makes it impossible to find the objectively best plan.

The solution for this problem is to properly integrate boolean normalization into the planning process having a rule to e.g. generate the CNF and a different one to generate the DNF.

**Comment by MMcM** [comment]
Related to #1004.
