### ISSUE TITLE
how to get the exact data in fdb?

### ISSUE THREAD

**Issue by CodingSuen** [FoundationDB/fdb-record-layer#1726]
Hi I am in need of mapping the data from record layer to foundationdb. For example，save a record by record layer, then find a way to fetch the exact value in fdb by the command get.

**Comment by MMcM** [comment]
1. Need to understand / control the record store prefix(es), at the beginning of every key-value pair.
    a. This might be controlled by a `Subspace` or `KeySpacePath`, which might involve using a directory layer for interning.
3. Need to understand the top-level organization of a record store in `FDBRecordStoreKeyspace`.
    a. Records proper live at `RECORD`, which is `1`.
5. Need to understand / control the record's type definition's primary key fields.
6. If records can be split, need to understand the splitter key suffix encoding and be prepared to reassemble.
7. Need to understand the FDB `Tuple` encoding used to put those together.
    a. This is implemented by all language bindings, but not by `fdbcli`, if that is what "command" means here.
9. Need to understand the Protobuf binary wire format used in the key's value to encode the actual record.

**Comment by CodingSuen** [comment]
> 1. Need to understand / control the record store prefix(es), at the beginning of every key-value pair.
>        a. This might be controlled by a `Subspace` or `KeySpacePath`, which might involve using a directory layer for interning.
> 
>     2. Need to understand the top-level organization of a record store in `FDBRecordStoreKeyspace`.
>        a. Records proper live at `RECORD`, which is `1`.
> 
>     3. Need to understand / control the record's type definition's primary key fields.
> 
>     4. If records can be split, need to understand the splitter key suffix encoding and be prepared to reassemble.
> 
>     5. Need to understand the FDB `Tuple` encoding used to put those together.
>        a. This is implemented by all language bindings, but not by `fdbcli`, if that is what "command" means here.
> 
>     6. Need to understand the Protobuf binary wire format used in the key's value to encode the actual record.



> 1. Need to understand / control the record store prefix(es), at the beginning of every key-value pair.
>        a. This might be controlled by a `Subspace` or `KeySpacePath`, which might involve using a directory layer for interning.
> 
>     2. Need to understand the top-level organization of a record store in `FDBRecordStoreKeyspace`.
>        a. Records proper live at `RECORD`, which is `1`.
> 
>     3. Need to understand / control the record's type definition's primary key fields.
> 
>     4. If records can be split, need to understand the splitter key suffix encoding and be prepared to reassemble.
> 
>     5. Need to understand the FDB `Tuple` encoding used to put those together.
>        a. This is implemented by all language bindings, but not by `fdbcli`, if that is what "command" means here.
> 
>     6. Need to understand the Protobuf binary wire format used in the key's value to encode the actual record.

**Comment by CodingSuen** [comment]
The issue is closed.
