### ISSUE TITLE
PlanOrderingKey.mergedComparisonKey too strict about fields between requested ordering and primary key

### ISSUE THREAD

**Issue by MMcM** [FoundationDB/fdb-record-layer#2336]
Given an index on `a, b, c, d` on a record type with primary key `k`, and a query with equality on `a`, disjunct of equality on `b`, and sort on `c`, the subplans are rejected because the candidate key `[a, b, k]` and `[a, b, c, d, k]` don't align well enough for it. But provided `c` and `d` are 1:1 with `k` (that is, not repeated / `createsDuplicates`), the actual (common) `planOrderingKey` will work. Such a Union will do extra comparing of these fields which ideally would be eliminated (by returning the candidate?) but is otherwise harmless. When the same pkey is on both sides, the extraneous fields will always match as well, I believe.

**Comment by normen662** [comment]
Can you check if the Cascades planner does with a similar query?

**Comment by MMcM** [comment]
The Cascades planner fails for this query. It can do a simpler one with only the or'ed condition on `a` and sorted by `b`, which also failed the heuristic planner. The union key produced, `[_.b, _.a, _.c, _.d, _.k]`, is longer than it needs to be, along the lines of the above description.
