### ISSUE TITLE
Extra read-only transactions resolving test(?) key space path

### ISSUE THREAD

**Issue by MMcM** [FoundationDB/fdb-record-layer#251]
As of f5378dc835369a7102d6a3a0345003ff677d24a0, that is, prior to #161, simple tests like `FDBRecordStoreTest.writeRead` would commit 4 read-only transactions (plus 2 read-write) for setup and the first `try` block and 1 read-only for the second `try` block. As of 836509650992f37b632114f493984d496f6a1a53, it is 7 and 4. I believe that the 3 extras correspond to the length of the path.

If anything, I would have thought that passing an open context to `toSubspace` / `toTuple` would mean that new transactions would never appear.

Perhaps this is specific to how `TestKeySpace` works and not an issue for real key spaces. Or perhaps the test environment doesn't have caching fully set up.

It seems a little unfortunate that we need `SubspaceProviderByKeySpacePath` rather than resolving the `SubspaceProvider` with the current context. As a consequence, `FDBRecordStoreBuilder.setKeySpacePath` still requires that the context be set first. It seems that it ought to now be possible to make a store builder with a path that gets cloned and then resolved per context. Though perhaps this is only really an issue of the second context is open on a different cluster.

**Comment by scgray** [comment]
[commit_analysis_part1.txt](https://github.com/FoundationDB/fdb-record-layer/files/2818223/commit_analysis_part1.txt)

I have started an analysis and wanted to drop my notes here, @jaydunk, you may want to take a look at this as well as it appears as if the resolver caches may not be doing their job.

**Comment by scgray** [comment]
The above analysis was for all the code involved in initializing the test and completing the first `try` block in `writeRead()`.  I did a similar analysis of the second `try` block that that reads the record back and the results are similar...there are three read-only transactions committed to read the keys of the `KeySpacePath`.  I further instrumented `LocatableResolver.resolveWithCache()` to verify whether or not the cache is being used, that is is the same cache during all calls and what I see is this:

Setup

    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: record-test]->Value: 1871, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: unit]->Value: 1566, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: recordStore]->Value: 1825, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: unit] IN CACHE 1037036090
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: recordStore] IN CACHE 1037036090

First `try` block

    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: record-test]->Value: 1871, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: recordStore]->Value: 1825, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: unit]->Value: 1566, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: record-test] IN CACHE 1037036090
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: recordStore] IN CACHE 1037036090
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: unit] IN CACHE 1037036090

Second and first `try()` block

    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: record-test]->Value: 1871, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: recordStore]->Value: 1825, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: record-test] IN CACHE 1037036090
    c.a.f.r.p.f.k.LocatableResolver - NOT IN CACHE 1037036090, READING [scope: ExtendedDirectoryLayer:GLOBAL, data: unit]->Value: 1566, metadata: null
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: recordStore] IN CACHE 1037036090
    c.a.f.r.p.f.k.LocatableResolver - PUT [scope: ExtendedDirectoryLayer:GLOBAL, data: unit] IN CACHE 1037036090

The `1037036090` is the `System.identityHashCode()` applied to the cache to ensure that it is the same cache every time.  So it appears that although we are putting entries into the cache they aren't found on subsequent lookups....more digging to follow.

**Comment by scgray** [comment]
I think I found the issue.  The default value for the `FDBDatabaseFactory.directoryCacheSize()` is zero (no caching).  @jaydunk is there any reason you can think of not to give this a default that isn't, you know, all zero-like?

**Comment by jaydunk** [comment]
No I don't think there's any reason not to change that to a sensible value
