### ISSUE TITLE
Allow for KeySpacePath to be set before FDBRecordContext in store builders

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#338]
The `FDBRecordStore.Builder` class currently doesn't allow for one to set the `KeySpacePath` before setting the `context`, as seen here:

https://github.com/FoundationDB/fdb-record-layer/blob/ad36ef9230fa85344d5388083301d8e5a096fc0f/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java#L2920-L2928

The reason for this is it uses the context to create a `SubspaceProvider` (by `KeySpacePath`) which needs the `context` to talk to the database to resolve any directory layer directories within the path.

The solution to this would be to do something like store a separate `keySpacePath` member in the builder and then create the provider at build time rather than when `setKeySpacePath` is called. (It could also do something fancy like only call `getSubspaceAsync` if the subspace provider is by `KeySpacePath` rather than by `Subspace`.) I think this removes one possible caching opportunity in that if one re-uses the same `FDBRecordStore.Builder`, the current implementation will cache the `SubspaceProvider` which, in turn, caches the `Subspace`. However, I'm not totally sure that's "good" caching in that if one provides a context from a different database, then one might expect to get a key space resolved against that database, but one will get it against the original. (So that might in and of itself be a bug.)

This came up when looking at a fix for our example code: PR #337.

**Comment by MMcM** [comment]
If `SubspaceProvider.getSubspace[Async]` took a `context` argument like `KeySpacePath.toSubspace[Async]`, then `SubspaceProviderByKeySpacePath.context` could be non-final and it could act as a one-entry cache keyed by that, instead of being constructed with it.

**Comment by MMcM** [comment]
Oh. but `recordStore.asBuilder` isn't quite right then. You don't want them sharing the one-entry cache. Maybe `FDBRecordStore` should just remember the `Subspace` itself, so that `KeySpacePath` can implement `SubspaceProvider`.

Also, with any logging we won't meet the goal of avoiding ever calling the resolver a second time. So maybe it should have `loggableString(Subspace)`.

In any case, it seems like an overhaul of the interface is the key to fixing this.
