### ISSUE TITLE
Set a default extension registry within an FDBMetaDataStore 

### ISSUE THREAD

**Issue by amouehsan** [FoundationDB/fdb-record-layer#352]
User has to set the extensionRegistry in an FDBMetaDataStore to avoid null pointer exceptions if proto is version 3. This was discovered while working on issue #3 (PR #320). Lets have an issue to track setting a default extension registry within an FDBMetaDataStore to avoid every client having to do the same.

**Comment by alecgrieser** [comment]
I think what I want this to do is to provide an extension registry that registers extension options from `record_metadata_options.proto`. For the most part, this only matters when the extension option to set the union descriptor is used, I suppose.
