### ISSUE TITLE
Plan AND predicates with an unordered intersection

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#361]
Once #336 is resolved, another step to getting the new planner to feature completeness is being able to plan AND queries. This is somewhat more delicate that #359 as OR predicates kind of have to be planned with some kind of union (uh, with a few caveats), but AND predicates can be planned in a myriad of ways including by applying residual filters on the result stream or using multiple fields in a compound index. (In some sense, that (and getting results ordered appropriately) are the whole reason to use compound indexes.) But as a back stop, the planner can use unordered intersections to merge results together, and it gets some progress on the planner going.

Whether this rule is actually a good heuristic going forward is...an interesting question. If it saves record resolves, then maybe it's good. It might be the case that this rule has some kind of weird priority or maybe the user should hint that they want this rule applied (or something).

**Comment by normen662** [comment]
This is done.
