### ISSUE TITLE
Convert tests to new RecordCursor API

### ISSUE THREAD

**Issue by nschiefer** [FoundationDB/fdb-record-layer#428]
We have hundreds of tests that use the old `AsyncIterator`-style methods to advance a `RecordCursor`. Before we deprecate those methods in #368, we need to move all the tests away from that.

As a bridge, we could use the `RecordCursorIterator`, which is currently sitting on a [branch](https://github.com/nschiefer/fdb-record-layer/tree/record-cursor-as-iterator) and can minimize the amount of rewriting.

**Comment by nschiefer** [comment]
@amouehsan I'm going to prepare the branch I have now, but without the deprecations, and get it merged into master. Then it can act as a starting point for your work here.

**Comment by amouehsan** [comment]
@nschiefer sounds good. thanks.

**Comment by amouehsan** [comment]
Passing this to Alec, who has already started working on this.

**Comment by alecgrieser** [comment]
Ah, in fact, resolved with #431.
