### ISSUE TITLE
Unreported exception error when building freshly checked out project with Intellij

### ISSUE THREAD

**Issue by giorgio-v** [FoundationDB/fdb-record-layer#463]
Hi,
Just getting started here, so it may be I’m missing something obvious. 

I cloned and setup the project following [the building guide](https://github.com/FoundationDB/fdb-record-layer/blob/master/docs/Building.md). Everything seems to work correctly with `gradle`, but I’m getting an error when I try to build the project from Intellij:

```
error: unreported exception X; must be caught or declared to be thrown
where X,T are type-variables:
X extends Throwable declared in method <X>orElseThrow(Supplier<? extends X>)
T extends Object declared in class Optional
```

As far as I can tell the problem is not due to Intellij configuration nor to the version of JDK (I see the same error from 8 to 11). 

The fix seems just a matter of adding the requested type annotation. I have patch ready, but I wanted to first open the issue and make sure the problem is real.

**Comment by scgray** [comment]
Hi Giorgio, which version of Intellij are you running?  I just re-checked out the latest master branch and set up with IntelliJ 2018.3.5 and Java 1.0.8_201 and I don't get any such errors.  Can you also share the location of the compile error?   If the type annotation you refer to may make sense to add anyway, but unfortunately I cannot replicate the problem you are seeing.

**Comment by giorgio-v** [comment]
Hey Scott,

Here’s the version info:

> IntelliJ IDEA 2018.3.5 (Community Edition)
> Build #IC-183.5912.21, built on February 26, 2019
> JRE: 1.8.0_152-release-1343-b28 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.3

And here are the links:

https://github.com/giorgio-v/fdb-record-layer/blob/c6305ab8e6412bddd53989796c271830f74959ef/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java#L154

https://github.com/giorgio-v/fdb-record-layer/blob/c6305ab8e6412bddd53989796c271830f74959ef/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java#L170

https://github.com/giorgio-v/fdb-record-layer/blob/c6305ab8e6412bddd53989796c271830f74959ef/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/keyspace/LocatableResolver.java#L193

**Comment by scgray** [comment]
Thanks Giorgio.  Do you also get this error compiling directly with gradle?

**Comment by MMcM** [comment]
Do tests like those in https://bugs.openjdk.java.net/browse/JDK-8165147 and associated also have problems in your setup?

**Comment by giorgio-v** [comment]
@scgray No, `./gradlew build` is successful. @MMcM Yeah, I saw that bug report. I’ll try to reproduce it locally and get back to you.

**Comment by giorgio-v** [comment]
@MMcM The Intellij project included here doesn’t build on my machine, unless I apply one of the workarounds described in 
https://bugs.openjdk.java.net/browse/JDK-8165147
[issue-463.zip](https://github.com/FoundationDB/fdb-record-layer/files/2989522/issue-463.zip)

**Comment by giorgio-v** [comment]
@MMcM Was the IntelliJ sample project useful? May I (or should I, don’t know) go ahead a open a PR or at least push a branch to my copy of the repo so that you can see the proposed changes?

Please let me know :)

**Comment by MMcM** [comment]
Since you have the same problem with this unrelated sample project and since that was fixed and others can build the Record Layer, I think we should concentrate on getting things working there. Even if we changed source code, we could inadvertently introduce a similar problem later.

I cannot tell from just the project directories in the .zip file precisely what Java SDK was used. The `misc.xml` has
```
<component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK">
```
so we need to know what `1.8` resolves to on your machine.

What version is it _specifically_? Or, can you send along your `jdk.table.xml`?

**Comment by giorgio-v** [comment]
@MMcM Hey, I completely missed the notification, sorry about that. 

Here’s my `jdk.table.xml`
[jdk.table.xml.zip](https://github.com/FoundationDB/fdb-record-layer/files/3039325/jdk.table.xml.zip)

**Comment by giorgio-v** [comment]
@MMcM Any news on this? Do you some other info or data from me? I’d like to solve this issue, if at all possible, so that I can try to take a look at other issues labeled as good for newcomers.

Thank you!

**Comment by MMcM** [comment]
1.8 on your machine is 8u60. That is pretty seriously out of date; the current version is 8u212.

(The 152 from earlier in this thread is what the IDE itself runs with.)

I was trying to figure out how to get that older version to confirm the problem, but Oracle's new licensing makes that challenging. I suggest, therefore, that you try upgrading.

**Comment by giorgio-v** [comment]
Just updated _both_ Intellij and the JDK and, as far as I can tell, it seems to be related to the IDE since I build the project just fine, with both 8u60 and 8u212.

I think I close this issue? Please let me know.

**Comment by MMcM** [comment]
Yes. If you are unblocked, go ahead and close this.

**Comment by giorgio-v** [comment]
Cool, thank @MMcM @scgray for helping me out!
