### ISSUE TITLE
Queries with order-preserving filter sorting by primary key will not use index for filter

### ISSUE THREAD

**Issue by nschiefer** [FoundationDB/fdb-record-layer#5]
Suppose we have a schema like:
```
message MyRecord {
   optional int64 id = 1 [(field).primary_key = true];
   optional int64 value = 2 [(field).index = {}];
}
```
Then suppose someone has a query like:
```
RecordQuery query = RecordQuery.newBuilder()
    .setRecordType("MyRecord")
    .setFilter(Query.field("value").equalsValue(5L))
    .setSort(Key.Expressions.field("id"))
    .build();
```
Without the sort, the returned plan will be something like `Index(MyRecord$value [[5],[5]])`, which is correct. However, *with* the sort, this will do `Scan(<,>) | [MyRecord] | value EQUALS 5` (i.e., it does a full store scan instead of using the index). But because the sort is by primary key and the filter is an equality comparison, the results of the index scan will be returned in the correct order, so it would be better to return the index scan instead (just like if there was no sort).

Note that if the filter had been something like `Query.field("value").greaterThan(5)`, then this optimization cannot be made.

A slightly more sophisticated example of this can occur if there are multiple filters. For example:
```
message MyRecord {
   optional int64 id = 1 [(field).primary_key = true];
   optional int64 value = 2 [(field).index = {}];
   optional int64 unindexed_value = 3;
}
```
Then the query:
```
RecordQuery query = RecordQuery.newBuilder()
    .setRecordType("MyRecord")
    .setFilter(Query.and(Query.field("value").equalsValue(5L), Query.field("unindexed_value").equalsValue(6L))
    .setSort(Key.Expressions.field("id"))
    .build();
```
The query plan should use the index on value then manually filter out the `unindexed_value` results.

**Comment by MMcM** [comment]
Should be taken care of by #1138.
