### ISSUE TITLE
Remove the static loadRecordStoreStateAsync methods

### ISSUE THREAD

**Issue by amouehsan** [FoundationDB/fdb-record-layer#559]
At #534 we deprecated the methods, and now it's time to drop them. As mentioned in #534 , `loadRecordStoreStateAsync` used to be static because in past open method was static on the record store instead of non-static on the builder. But it creates confusions now. Lets drop it.

**Comment by alecgrieser** [comment]
Closing now that #560 is merged into the 2.7 branch.
