### ISSUE TITLE
Store header lastUpdateTime isn't being set any more

### ISSUE THREAD

**Issue by MMcM** [FoundationDB/fdb-record-layer#569]
Looks to have gotten lost from https://github.com/FoundationDB/fdb-record-layer/pull/536/files#diff-8852223096de069e9ac9e9d37b600accL1550. I'm not sure whether the intent was to have `saveStoreHeader` do it (which would require a change to its signature).

**Comment by alecgrieser** [comment]
I think this is a duplicate of #593, which was fixed with #594.
