### ISSUE TITLE
Add slf4j dependency in fdb-extensions

### ISSUE THREAD

**Issue by nblintao** [FoundationDB/fdb-record-layer#680]
Add `org.slf4j` dependency in `fdb-extensions` so `SynchronizedSession` can be moved there.

**Comment by nblintao** [comment]
This is one of the TODOs after https://github.com/FoundationDB/fdb-record-layer/pull/638

**Comment by alecgrieser** [comment]
Merged into 2.8 with #687

**Comment by nblintao** [comment]
Merged into 2.8 with https://github.com/FoundationDB/fdb-record-layer/pull/686 actually:)

**Comment by alecgrieser** [comment]
Oops, right
