### ISSUE TITLE
Load online indexer configuration parameters during index rebuild

### ISSUE THREAD

**Issue by amouehsan** [FoundationDB/fdb-record-layer#731]
At the moment, the online indexer is passed a set of configuration parameters (such as max number of retries) only before the indexer attempts to build. That means that if these parameters change during rebuild, the indexer will not pick them up. It would be good if we had a way for the indexer to pick up the updated parameters, every some time, e.g., in the beginning of each transaction.

**Comment by nblintao** [comment]
This has been resolved in https://github.com/FoundationDB/fdb-record-layer/pull/732
