### ISSUE TITLE
deleteRecordsWhere not working

### ISSUE THREAD

**Issue by laptopisasset** [FoundationDB/fdb-record-layer#786]
HI guys i am trying to delete records with deleteRecordsWhere it returns exception,
record type version of deleteRecordsWhere can only be used when all record types have a type prefix

**Comment by scgray** [comment]
Hi, hopefully I get the description of what is going on correct here.  Others more knowledgeable can chime in if I get a detail wrong...

This is because you are a using a `RecordTypeKeyComparison` in your query, but your primary key does not actually include the record type in it.

As discussed [here](https://github.com/FoundationDB/fdb-record-layer/blob/master/docs/FAQ.md), under **Are record types tables?**, by default records of all types are intermingled together in the same extent.  This means that if you have two record types like:

```
message Type1 {
    required int64 thisField = 1 [(com.apple.foundationdb.record.field).primary_key = true];
}
message Type2 {
    required int64 thatField = 1 [(com.apple.foundationdb.record.field).primary_key = true];
}
```

And, then you write a record of `Type1(thisField = 1)` followed by `Type2(thatField = 1)`, the second record will overwrite the first record, even though they are different record types (this is a source of confusion for almost everyone coming from the traditional relational world). 

For those that want to have a more traditional model of the world, in which records are discretely separated by record type, you need to define your primary key to include the record type in it as well, such as:

```
import static com.apple.foundationdb.record.metadata.Key.Expressions.concat;
import static com.apple.foundationdb.record.metadata.Key.Expressions.recordType;
import static com.apple.foundationdb.record.metadata.Key.Expressions.field;
...
metadata.getRecordType("Type1").setPrimaryKey(concat(recordType(), field("thisField")));
metadata.getRecordType("Type2").setPrimaryKey(concat(recordType(), field("thatField")));
```

This will make sure that your primary key values include the record type in it to disambiguate records of the different types and allowing you to use the `RecordTypeKeyComparison`.

**Comment by laptopisasset** [comment]
Thanks for the help @scgray, Is there any way to define a property in protobuf which will make sure that record layer automatically concates the record-type with primary key, and what to record_type_key in record meta data options do.

**Comment by laptopisasset** [comment]
And Actually Speaking, I Cannot access setPrimaryKey method from RecordType
metadata.getRecordType("Type1").setPrimaryKey(concat(recordType(), field("thisField")));

**Comment by laptopisasset** [comment]
import com.apple.foundationdb.record.RecordMetaData;
import com.apple.foundationdb.record.RecordMetaDataBuilder;
import com.apple.foundationdb.record.provider.foundationdb.FDBDatabase;
import com.apple.foundationdb.record.provider.foundationdb.FDBDatabaseFactory;
import com.apple.foundationdb.record.provider.foundationdb.FDBRecordStore;
import com.apple.foundationdb.record.provider.foundationdb.FDBStoredRecordBuilder;
import com.apple.foundationdb.record.provider.foundationdb.keyspace.DirectoryLayerDirectory;
import com.apple.foundationdb.record.provider.foundationdb.keyspace.KeySpace;
import com.apple.foundationdb.record.provider.foundationdb.keyspace.KeySpaceDirectory;
import com.apple.foundationdb.record.provider.foundationdb.keyspace.KeySpacePath;
import com.crud.recordLayer.TestRecords1Proto;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static com.apple.foundationdb.record.metadata.Key.Expressions.*;


public class Crud {
    static FDBDatabase fdb;
    static KeySpace keySpace;
    static KeySpacePath path;
    static RecordMetaDataBuilder builder;

    @BeforeAll
    public static void setUp() {
        fdb = FDBDatabaseFactory.instance().getDatabase();
        keySpace = new KeySpace(new DirectoryLayerDirectory("application")
            .addSubdirectory(new KeySpaceDirectory("environment", KeySpaceDirectory.KeyType.STRING))
        );
        path = keySpace.path("application", "com.crud.test").add("environment", "test");

        builder = RecordMetaData.newBuilder().setRecords(TestRecords1Proto.getDescriptor());
    }

    @Test
    public void insertData() {
        builder.getRecordType("MySimpleRecord").setPrimaryKey(concat(recordType(), field("rec_no")));
        FDBRecordStore.Builder recordStoreBuilder = FDBRecordStore.newBuilder().setMetaDataProvider(builder.getRecordMetaData()).setKeySpacePath(path);
        fdb.run(cx -> {
            FDBRecordStore store = recordStoreBuilder.copyBuilder().setContext(cx).createOrOpen();
            store.saveRecord(TestRecords1Proto.MySimpleRecord.newBuilder().setRecNo(100L).setStrValueIndexed("Soundhar").setNumValue2(20).setNumValue3Indexed(45).addAllRepeater(Arrays.asList(1, 3, 45, 6)).build());
            store.saveRecord(TestRecords1Proto.MySimpleRecord.newBuilder().setRecNo(100L).setStrValueIndexed("Gowtham").setNumValue2(30).setNumValue3Indexed(25).addAllRepeater(Arrays.asList(1, 3, 45, 6)).build());
            store.saveRecord(TestRecords1Proto.MySimpleRecord.newBuilder().setRecNo(100L).setStrValueIndexed("Mathan").setNumValue2(40).setNumValue3Indexed(35).addAllRepeater(Arrays.asList(1, 3, 45, 6)).build());
            store.saveRecord(TestRecords1Proto.MySimpleRecord.newBuilder().setRecNo(100L).setStrValueIndexed("Natarajan").setNumValue2(50).setNumValue3Indexed(65).addAllRepeater(Arrays.asList(1, 3, 45, 6)).build());
            store.saveRecord(TestRecords1Proto.MySimpleRecord.newBuilder().setRecNo(100L).setStrValueIndexed("Jayanthi").setNumValue2(70).setNumValue3Indexed(75).addAllRepeater(Arrays.asList(1, 3, 45, 6)).build());
            return null;
        });

    }

    @Test
    public void deleteData() {
        builder.getRecordType("MySimpleRecord").setPrimaryKey(concat(recordType(), field("rec_no")));
        FDBRecordStore.Builder recordStoreBuilder = FDBRecordStore.newBuilder().setMetaDataProvider(builder.getRecordMetaData()).setKeySpacePath(path);
        fdb.run(cx -> {
            FDBRecordStore store = recordStoreBuilder.copyBuilder().setContext(cx).createOrOpen();
            store.deleteRecordsWhere("MySimpleRecord", null);
            return null;
        });
    }
}

This the code i am trying to execute same Error pops out again

**Comment by scgray** [comment]
Hi, no, there isn't anything as basic as a configuration option (may be worth opening an issue?).  Here is an example from one of the test cases:

https://github.com/FoundationDB/fdb-record-layer/blob/1c0399fc023db12faa0aa1aa59851f53b7c5ad46/fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RecordTypeKeyTest.java#L91

I think one thing you could do is to use a metadata hook like this in a similar fashion, iterate over your records, fetch their primary key, and concatenate the record type onto each one.  This could probably be done in a relatively small bit of code.
