### ISSUE TITLE
FunctionKeyExpressions are not honored in Query Planning

### ISSUE THREAD

**Issue by rahul-nitkkr** [FoundationDB/fdb-record-layer#818]
```FunctionKeyExpression``` don't seem to be honored in the evaluation of a query plan.
We came across a  [test case](https://github.com/FoundationDB/fdb-record-layer/blob/b4e1e7211d07c361003581dd9652a3f60fa4a6ca/fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FunctionKeyIndexTest.java)which exposes this .
Is there any plan to make FunctionKeyExpressions allowed to be picked for indexes ? 
Are there any workarounds for the same ?

**Comment by MMcM** [comment]
That test is out of date. Function indexes do with in queries when used simply. And `SubstrFunction` needs to be a `QueryableKeyExpression`.

**Comment by MMcM** [comment]
I will update the test.
