### ISSUE TITLE
gradle.properties refresh

### ISSUE THREAD

**Issue by MMcM** [FoundationDB/fdb-record-layer#900]
There are newer versions in Maven Central. Nothing looks to have advanced majorly, but it's probably best to update from time to time.

**Comment by alecgrieser** [comment]
Let's try and get as much as possible of this into 2.9 so that people are more attuned to looking for any upgrades just in case a downstream dependency clashes somehow. This might also mean we upgrade all of the dependencies except for, say, guava and protobuf.

**Comment by alecgrieser** [comment]
Resolved with #912.
