### ISSUE TITLE
Replace RelationalExpressionPointerSet with Guava classes

### ISSUE THREAD

**Issue by nschiefer** [FoundationDB/fdb-record-layer#940]
The implementation of the experimental planner's Memo data structure includes the `RelationalExpressionPointerSet` (originally `PlannerExpressionPointerSet`), which is basically just a set that always uses reference equality, rather than the built-in `equals()` method.

@normen662 tells me that this can be done using Guava classes, which is vastly preferable. We should replace `RelationalExpressionPointerSet`, if possible.

**Comment by normen662** [comment]
Done.
