### ISSUE TITLE
RecordMetaData#recordTypesForIndex is N^2 with Universal Index probing.

### ISSUE THREAD

**Issue by jleach4** [FoundationDB/fdb-record-layer#977]
I have a query with 32 an/or predicates with 8 indexes.  The current planner just spins on CPU on the query hotspotting on RecordMetaData#recordTypesForIndex.

![Screen Shot 2020-06-17 at 4 52 36 PM](https://user-images.githubusercontent.com/1850293/84962150-fa6bdd00-b0ba-11ea-9e56-00f104f3cc52.png)

**Comment by MMcM** [comment]
I thought the number of universal indexes was typically one or zero, but apparently due to some simplifications elsewhere it's now eleven or twelve.
